<?php

declare(strict_types=1);

namespace Omnipay\MsaQuickpay\Message;

class PurchaseResponse extends AbstractResponse
{
    /**
     * Gateway Reference
     *
     * A reference provided by the gateway to represent this transaction
     */
    public function getTransactionReference(): ?string
    {
        return $this->data['ReceiptNumber'] ?? null;
    }

    /**
     * Get the transaction ID as generated by the merchant website.
     */
    public function getTransactionId(): ?string
    {
        return null;
    }
}
